version: '3.1'
services:
  db: 
    image: mysql:8.1.0
    environment:
      MYSQL_USER: sobunge
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ispdb
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3309/MYSQL_DATABASE
      SPRING_DATASOURCE_USERNAME: MYSQL_USER
      SPRING_DATASOURCE_PASSWORD: MYSQL_PASSWORD
    ports:
      - 3309:3306
